remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

navigation:
  - name: URL Shortner
    link: ./index.html
    sublist:
      - name: Features
        link: ./index.html#features
      - name: API Usage
        link: ./index.html#api-usage
  - name: Installation
    link: ./installation.html
